local unit_energy = {
    amphaa = {energyMake = 1}, -- Angler
    amphassault = {energyMake = 1}, -- Grizzly
    amphbomb = {energyMake = 1}, -- Limpet
    amphfloater = {energyMake = 1}, -- Buoy
    amphimpulse = {energyMake = 1}, -- Archer
    amphlaunch = {energyMake = 1}, -- Lobster
    amphraid = {energyMake = 1}, -- Duck
    amphriot = {energyMake = 1}, -- Scallop
    bomberdisarm = {energyMake = 1}, -- Thunderbird
    bomberheavy = {energyMake = 1}, -- Likho
    bomberprec = {energyMake = 1}, -- Raven
    bomberriot = {energyMake = 1}, -- Phoenix
    bomberstrike = {energyMake = 1}, -- Kestrel
    chicken = {energyMake = 1}, -- Chicken
    chicken_blimpy = {energyMake = 1}, -- Blimpy
    chicken_digger = {energyMake = 1}, -- Digger
    chicken_dodo = {energyMake = 1}, -- Dodo
    chicken_dragon = {energyMake = 1}, -- Dragon
    chicken_leaper = {energyMake = 1}, -- Leaper
    chicken_pigeon = {energyMake = 1}, -- Rafflesia
    chicken_roc = {energyMake = 1}, -- Roc
    chicken_shield = {energyMake = 1}, -- Blooper
    chicken_spidermonkey = {energyMake = 1}, -- Spidermonkey
    chicken_tiamat = {energyMake = 1}, -- Tiamat
    chickena = {energyMake = 1}, -- Cockatrice
    chickenblobber = {energyMake = 1}, -- Blobber
    chickenc = {energyMake = 1}, -- Basilisk
    chickenf = {energyMake = 1}, -- Talon
    chickenr = {energyMake = 1}, -- Lobber
    chickens = {energyMake = 1}, -- Spiker
    chickenwurm = {energyMake = 1}, -- Wurm
    cloakaa = {energyMake = 1}, -- Gremlin
    cloakarty = {energyMake = 1}, -- Sling
    cloakassault = {energyMake = 1}, -- Knight
    cloakbomb = {energyMake = 1}, -- Imp
    cloakheavyraid = {energyMake = 1}, -- Scythe
    cloakjammer = {energyMake = 1}, -- Iris
    cloakraid = {energyMake = 1}, -- Glaive
    cloakriot = {energyMake = 1}, -- Reaver
    cloakskirm = {energyMake = 1}, -- Ronin
    cloaksnipe = {energyMake = 1}, -- Phantom
    dronecarry = {energyMake = 1}, -- Gull
    dronefighter = {energyMake = 1}, -- Spicula
    droneheavyslow = {energyMake = 1}, -- Viper
    dronelight = {energyMake = 1}, -- Firefly
    grebe = {energyMake = 1}, -- Grebe
    gunshipaa = {energyMake = 1}, -- Trident
    gunshipassault = {energyMake = 1}, -- Revenant
    gunshipbomb = {energyMake = 1}, -- Blastwing
    gunshipemp = {energyMake = 1}, -- Gnat
    gunshipheavyskirm = {energyMake = 1}, -- Nimbus
    gunshipkrow = {energyMake = 1}, -- Krow
    gunshipraid = {energyMake = 1}, -- Locust
    gunshipskirm = {energyMake = 1}, -- Harpy
    hoveraa = {energyMake = 1}, -- Flail
    hoverarty = {energyMake = 1}, -- Lance
    hoverassault = {energyMake = 1}, -- Halberd
    hoverdepthcharge = {energyMake = 1}, -- Claymore
    hoverheavyraid = {energyMake = 1}, -- Bolas
    hoverraid = {energyMake = 1}, -- Dagger
    hoverriot = {energyMake = 1}, -- Mace
    hoverskirm = {energyMake = 1}, -- Scalpel
    jumpaa = {energyMake = 1}, -- Toad
    jumparty = {energyMake = 1}, -- Firewalker
    jumpassault = {energyMake = 1}, -- Jack
    jumpblackhole = {energyMake = 1}, -- Placeholder
    jumpbomb = {energyMake = 1}, -- Skuttle
    jumpraid = {energyMake = 1}, -- Pyro
    jumpscout = {energyMake = 1}, -- Puppy
    jumpskirm = {energyMake = 1}, -- Moderator
    jumpsumo = {energyMake = 1}, -- Jugglenaut
    nebula = {energyMake = 1}, -- Nebula
    planefighter = {energyMake = 1}, -- Swift
    planeheavyfighter = {energyMake = 1}, -- Raptor
    planescout = {energyMake = 1}, -- Owl
    shieldaa = {energyMake = 1}, -- Vandal
    shieldarty = {energyMake = 1}, -- Racketeer
    shieldassault = {energyMake = 1}, -- Thug
    shieldbomb = {energyMake = 1}, -- Snitch
    shieldfelon = {energyMake = 1}, -- Felon
    shieldraid = {energyMake = 1}, -- Bandit
    shieldriot = {energyMake = 1}, -- Outlaw
    shieldscout = {energyMake = 1}, -- Dirtbag
    shieldshield = {energyMake = 1}, -- Aspis
    shieldskirm = {energyMake = 1}, -- Rogue
    spideraa = {energyMake = 1}, -- Tarantula
    spideranarchid = {energyMake = 1}, -- Anarchid
    spiderantiheavy = {energyMake = 1}, -- Widow
    spiderassault = {energyMake = 1}, -- Hermit
    spidercrabe = {energyMake = 1}, -- Crab
    spideremp = {energyMake = 1}, -- Venom
    spiderriot = {energyMake = 1}, -- Redback
    spiderscout = {energyMake = 1}, -- Flea
    spiderskirm = {energyMake = 1}, -- Recluse
    tankaa = {energyMake = 1}, -- Ettin
    tankarty = {energyMake = 1}, -- Emissary
    tankassault = {energyMake = 1}, -- Minotaur
    tankheavyarty = {energyMake = 1}, -- Tremor
    tankheavyassault = {energyMake = 1}, -- Cyclops
    tankheavyraid = {energyMake = 1}, -- Blitz
    tankraid = {energyMake = 1}, -- Kodachi
    tankriot = {energyMake = 1}, -- Ogre
    vehaa = {energyMake = 1}, -- Crasher
    veharty = {energyMake = 1}, -- Badger
    vehassault = {energyMake = 1}, -- Ravager
    vehcapture = {energyMake = 1}, -- Dominatrix
    vehheavyarty = {energyMake = 1}, -- Impaler
    vehraid = {energyMake = 1}, -- Scorcher
    vehriot = {energyMake = 1}, -- Ripper
    vehscout = {energyMake = 1}, -- Dart
    vehsupport = {energyMake = 1}, -- Fencer
}

return unit_energy