local metalmult = (tonumber(Spring.GetModOptions().metalmult) or 1) * 2

local VERY_EFFICIENT = {2 * metalmult, "Very Efficient"}
local EFFICIENT = {1.5 * metalmult, "Efficient"}
local NORMAL = {1 * metalmult, "Average"}
local TERRIBLE = {0.5 * metalmult, "Terrible"}
local USELESS = {0 * metalmult, "Useless"}

local unitEnergyMulti = {
    amphaa = NORMAL, -- Angler
    amphassault = TERRIBLE, -- Grizzly
    amphbomb = TERRIBLE, -- Limpet
    amphfloater = TERRIBLE, -- Buoy
    amphimpulse = NORMAL, -- Archer
    amphlaunch = USELESS, -- Lobster
    amphraid = VERY_EFFICIENT, -- Duck
    amphriot = NORMAL, -- Scallop
    bomberdisarm = TERRIBLE, -- Thunderbird
    bomberheavy = TERRIBLE, -- Likho
    bomberprec = VERY_EFFICIENT, -- Raven
    bomberriot = NORMAL, -- Phoenix
    bomberstrike = TERRIBLE, -- Kestrel
    chicken = NORMAL, -- Chicken
    chicken_blimpy = NORMAL, -- Blimpy
    chicken_digger = VERY_EFFICIENT, -- Digger
    chicken_dodo = NORMAL, -- Dodo
    chicken_dragon = USELESS, -- Dragon
    chicken_leaper = NORMAL, -- Leaper
    chicken_pigeon = NORMAL, -- Rafflesia
    chicken_roc = NORMAL, -- Roc
    chicken_shield = EFFICIENT, -- Blooper
    chicken_spidermonkey = EFFICIENT, -- Spidermonkey
    chicken_tiamat = TERRIBLE, -- Tiamat
    chickena = EFFICIENT, -- Cockatrice
    chickenblobber = USELESS, -- Blobber
    chickenc = EFFICIENT, -- Basilisk
    chickenf = EFFICIENT, -- Talon
    chickenr = TERRIBLE, -- Lobber
    chickens = EFFICIENT, -- Spiker
    chickenwurm = NORMAL, -- Wurm
    cloakaa = NORMAL, -- Gremlin
    cloakarty = TERRIBLE, -- Sling
    cloakassault = TERRIBLE, -- Knight
    cloakbomb = NORMAL, -- Imp
    cloakheavyraid = EFFICIENT, -- Scythe
    cloakjammer = USELESS, -- Iris
    cloakraid = EFFICIENT, -- Glaive
    cloakriot = EFFICIENT, -- Reaver
    cloakskirm = EFFICIENT, -- Ronin
    cloaksnipe = NORMAL, -- Phantom
    dronecarry = EFFICIENT, -- Gull
    dronefighter = NORMAL, -- Spicula
    droneheavyslow = NORMAL, -- Viper
    dronelight = EFFICIENT, -- Firefly
    grebe = NORMAL, -- Grebe
    gunshipaa = NORMAL, -- Trident
    gunshipassault = NORMAL, -- Revenant
    gunshipbomb = VERY_EFFICIENT, -- Blastwing
    gunshipemp = EFFICIENT, -- Gnat
    gunshipheavyskirm = TERRIBLE, -- Nimbus
    gunshipkrow = TERRIBLE, -- Krow
    gunshipraid = VERY_EFFICIENT, -- Locust
    gunshipskirm = EFFICIENT, -- Harpy
    hoveraa = NORMAL, -- Flail
    hoverarty = USELESS, -- Lance
    hoverassault = TERRIBLE, -- Halberd
    hoverdepthcharge = NORMAL, -- Claymore
    hoverheavyraid = EFFICIENT, -- Bolas
    hoverraid = VERY_EFFICIENT, -- Dagger
    hoverriot = NORMAL, -- Mace
    hoverskirm = TERRIBLE, -- Scalpel
    hoverminer = VERY_EFFICIENT, -- Dampener
    hovershotgun = NORMAL, -- Punisher
    jumpaa = NORMAL, -- Toad
    jumparty = USELESS, -- Firewalker
    jumpassault = TERRIBLE, -- Jack
    jumpblackhole = USELESS, -- Placeholder
    jumpbomb = VERY_EFFICIENT, -- Skuttle
    jumpraid = VERY_EFFICIENT, -- Pyro
    jumpscout = EFFICIENT, -- Puppy
    jumpskirm = NORMAL, -- Moderator
    jumpsumo = USELESS, -- Jugglenaut
    nebula = TERRIBLE, -- Nebula
    planefighter = VERY_EFFICIENT, -- Swift
    planeheavyfighter = EFFICIENT, -- Raptor
    planescout = USELESS, -- Owl
    shieldaa = NORMAL, -- Vandal
    shieldarty = TERRIBLE, -- Racketeer
    shieldassault = TERRIBLE, -- Thug
    shieldbomb = NORMAL, -- Snitch
    shieldfelon = TERRIBLE, -- Felon
    shieldraid = EFFICIENT, -- Bandit
    shieldriot = USELESS, -- Outlaw
    shieldscout = NORMAL, -- Dirtbag
    shieldshield = NORMAL, -- Aspis
    shieldskirm = NORMAL, -- Rogue
    spideraa = NORMAL, -- Tarantula
    spideranarchid = NORMAL, -- Anarchid
    spiderantiheavy = NORMAL, -- Widow
    spiderassault = NORMAL, -- Hermit
    spidercrabe = USELESS, -- Crab
    spideremp = EFFICIENT, -- Venom
    spiderriot = NORMAL, -- Redback
    spiderscout = NORMAL, -- Flea
    spiderskirm = NORMAL, -- Recluse
    striderantiheavy = NORMAL, -- Ultimatum
    striderarty = TERRIBLE, -- Merlin
    striderdante = TERRIBLE, -- Dante
    striderscorpion = NORMAL, -- Scorpion
    tankaa = NORMAL, -- Ettin
    tankarty = TERRIBLE, -- Emissary
    tankassault = TERRIBLE, -- Minotaur
    tankheavyarty = USELESS, -- Tremor
    tankheavyassault = USELESS, -- Cyclops
    tankheavyraid = EFFICIENT, -- Blitz
    tankraid = VERY_EFFICIENT, -- Kodachi
    tankriot = NORMAL, -- Ogre
    vehaa = NORMAL, -- Crasher
    veharty = USELESS, -- Badger
    vehassault = NORMAL, -- Ravager
    vehcapture = TERRIBLE, -- Dominatrix
    vehheavyarty = NORMAL, -- Impaler
    vehraid = EFFICIENT, -- Scorcher
    vehriot = NORMAL, -- Ripper
    vehscout = EFFICIENT, -- Dart
    vehsupport = TERRIBLE -- Fencer
}


return unitEnergyMulti
