-- Set chicken cost
-- for name, ud in pairs(UnitDefs) do
--     if (ud.unitname:sub(1,7) == "chicken") then
--         ud.buildcostmetal = ud.buildtime
--         ud.buildcostenergy = ud.buildtime
--     end
--     if (ud.unitname == "factorychicken") then
--         ud.buildoptions = {
--             [[factorychicken]],
--         }
--     end
-- end