local unit_energy = {
    amphaa = {customParams = { deploy_income = 10 }}, -- Angler
    amphassault = {customParams = { deploy_income = 4 }}, -- Grizzly
    amphbomb = {customParams = { deploy_income = 4 }}, -- Limpet
    amphfloater = {customParams = { deploy_income = 6 }}, -- Buoy
    amphimpulse = {customParams = { deploy_income = 5 }}, -- Archer
    amphlaunch = {customParams = { deploy_income = 0 }}, -- Lobster
    amphraid = {customParams = { deploy_income = 6 }}, -- Duck
    amphriot = {customParams = { deploy_income = 6 }}, -- Scallop
    bomberdisarm = {customParams = { deploy_income = 4 }}, -- Thunderbird
    bomberheavy = {customParams = { deploy_income = 48 }}, -- Likho
    bomberprec = {customParams = { deploy_income = 15 }}, -- Raven
    bomberriot = {customParams = { deploy_income = 10 }}, -- Phoenix
    bomberstrike = {customParams = { deploy_income = 8 }}, -- Kestrel
    chicken = {customParams = { deploy_income = 2 }}, -- Chicken
    chicken_blimpy = {customParams = { deploy_income = 10 }}, -- Blimpy
    chicken_digger = {customParams = { deploy_income = 0 }}, -- Digger
    chicken_dodo = {customParams = { deploy_income = 4 }}, -- Dodo
    chicken_dragon = {customParams = { deploy_income = 2 }}, -- Dragon
    chicken_leaper = {customParams = { deploy_income = 2 }}, -- Leaper
    chicken_pigeon = {customParams = { deploy_income = 2 }}, -- Rafflesia
    chicken_roc = {customParams = { deploy_income = 2 }}, -- Roc
    chicken_shield = {customParams = { deploy_income = 10 }}, -- Blooper
    chicken_spidermonkey = {customParams = { deploy_income = 13 }}, -- Spidermonkey
    chicken_tiamat = {customParams = { deploy_income = 8 }}, -- Tiamat
    chickena = {customParams = { deploy_income = 6 }}, -- Cockatrice
    chickenblobber = {customParams = { deploy_income = 0 }}, -- Blobber
    chickenc = {customParams = { deploy_income = 8 }}, -- Basilisk
    chickenf = {customParams = { deploy_income = 1 }}, -- Talon
    chickenr = {customParams = { deploy_income = 0 }}, -- Lobber
    chickens = {customParams = { deploy_income = 12 }}, -- Spiker
    chickenwurm = {customParams = { deploy_income = 4 }}, -- Wurm
    cloakaa = {customParams = { deploy_income = 6 }}, -- Gremlin
    cloakarty = {customParams = { deploy_income = 2 }}, -- Sling
    cloakassault = {customParams = { deploy_income = 4 }}, -- Knight
    cloakbomb = {customParams = { deploy_income = 10 }}, -- Imp
    cloakheavyraid = {customParams = { deploy_income = 8 }}, -- Scythe
    cloakjammer = {customParams = { deploy_income = 0 }}, -- Iris
    cloakraid = {customParams = { deploy_income = 8 }}, -- Glaive
    cloakriot = {customParams = { deploy_income = 10 }}, -- Reaver
    cloakskirm = {customParams = { deploy_income = 6 }}, -- Ronin
    cloaksnipe = {customParams = { deploy_income = 4 }}, -- Phantom
    dronecarry = {customParams = { deploy_income = 1 }}, -- Gull
    dronefighter = {customParams = { deploy_income = 1 }}, -- Spicula
    droneheavyslow = {customParams = { deploy_income = 1 }}, -- Viper
    dronelight = {customParams = { deploy_income = 1 }}, -- Firefly
    grebe = {customParams = { deploy_income = 6 }}, -- Grebe
    gunshipaa = {customParams = { deploy_income = 12 }}, -- Trident
    gunshipassault = {customParams = { deploy_income = 12 }}, -- Revenant
    gunshipbomb = {customParams = { deploy_income = 4 }}, -- Blastwing
    gunshipemp = {customParams = { deploy_income = 3 }}, -- Gnat
    gunshipheavyskirm = {customParams = { deploy_income = 10 }}, -- Nimbus
    gunshipkrow = {customParams = { deploy_income = 10 }}, -- Krow
    gunshipraid = {customParams = { deploy_income = 4 }}, -- Locust
    gunshipskirm = {customParams = { deploy_income = 11 }}, -- Harpy
    hoveraa = {customParams = { deploy_income = 12 }}, -- Flail
    hoverarty = {customParams = { deploy_income = 4 }}, -- Lance
    hoverassault = {customParams = { deploy_income = 4 }}, -- Halberd
    hoverdepthcharge = {customParams = { deploy_income = 10 }}, -- Claymore
    hoverheavyraid = {customParams = { deploy_income = 8 }}, -- Bolas
    hoverraid = {customParams = { deploy_income = 8 }}, -- Dagger
    hoverriot = {customParams = { deploy_income = 12 }}, -- Mace
    hoverskirm = {customParams = { deploy_income = 14 }}, -- Scalpel
    hoverminer = {customParams = { deploy_income = 6 }}, -- Dampener
    hovershotgun = {customParams = { deploy_income = 6 }}, -- hovershotgun
    jumpaa = {customParams = { deploy_income = 4 }}, -- Toad
    jumparty = {customParams = { deploy_income = 0 }}, -- Firewalker
    jumpassault = {customParams = { deploy_income = 10 }}, -- Jack
    jumpblackhole = {customParams = { deploy_income = 0 }}, -- Placeholder
    jumpbomb = {customParams = { deploy_income = 12 }}, -- Skuttle
    jumpraid = {customParams = { deploy_income = 8 }}, -- Pyro
    jumpscout = {customParams = { deploy_income = 5 }}, -- Puppy
    jumpskirm = {customParams = { deploy_income = 10 }}, -- Moderator
    jumpsumo = {customParams = { deploy_income = 10 }}, -- Jugglenaut
    nebula = {customParams = { deploy_income = 20 }}, -- Nebula
    planefighter = {customParams = { deploy_income = 8 }}, -- Swift
    planeheavyfighter = {customParams = { deploy_income = 12 }}, -- Raptor
    planescout = {customParams = { deploy_income = 4 }}, -- Owl
    shieldaa = {customParams = { deploy_income = 8 }}, -- Vandal
    shieldarty = {customParams = { deploy_income = 0 }}, -- Racketeer
    shieldassault = {customParams = { deploy_income = 4 }}, -- Thug
    shieldbomb = {customParams = { deploy_income = 8 }}, -- Snitch
    shieldfelon = {customParams = { deploy_income = 5 }}, -- Felon
    shieldraid = {customParams = { deploy_income = 5 }}, -- Bandit
    shieldriot = {customParams = { deploy_income = 4 }}, -- Outlaw
    shieldscout = {customParams = { deploy_income = 4 }}, -- Dirtbag
    shieldshield = {customParams = { deploy_income = 4 }}, -- Aspis
    shieldskirm = {customParams = { deploy_income = 6 }}, -- Rogue
    spideraa = {customParams = { deploy_income = 10 }}, -- Tarantula
    spideranarchid = {customParams = { deploy_income = 8 }}, -- Anarchid
    spiderantiheavy = {customParams = { deploy_income = 4 }}, -- Widow
    spiderassault = {customParams = { deploy_income = 4 }}, -- Hermit
    spidercrabe = {customParams = { deploy_income = 2 }}, -- Crab
    spideremp = {customParams = { deploy_income = 10 }}, -- Venom
    spiderriot = {customParams = { deploy_income = 12 }}, -- Redback
    spiderscout = {customParams = { deploy_income = 4 }}, -- Flea
    spiderskirm = {customParams = { deploy_income = 5 }}, -- Recluse
    tankaa = {customParams = { deploy_income = 10 }}, -- Ettin
    tankarty = {customParams = { deploy_income = 8 }}, -- Emissary
    tankassault = {customParams = { deploy_income = 8 }}, -- Minotaur
    tankheavyarty = {customParams = { deploy_income = 0 }}, -- Tremor
    tankheavyassault = {customParams = { deploy_income = 4 }}, -- Cyclops
    tankheavyraid = {customParams = { deploy_income = 10 }}, -- Blitz
    tankraid = {customParams = { deploy_income = 6 }}, -- Kodachi
    tankriot = {customParams = { deploy_income = 14 }}, -- Ogre
    vehaa = {customParams = { deploy_income = 13 }}, -- Crasher
    veharty = {customParams = { deploy_income = 2 }}, -- Badger
    vehassault = {customParams = { deploy_income = 8 }}, -- Ravager
    vehcapture = {customParams = { deploy_income = 13 }}, -- Dominatrix
    vehheavyarty = {customParams = { deploy_income = 6 }}, -- Impaler
    vehraid = {customParams = { deploy_income = 8 }}, -- Scorcher
    vehriot = {customParams = { deploy_income = 11 }}, -- Ripper
    vehscout = {customParams = { deploy_income = 6 }}, -- Dart
    vehsupport = {customParams = { deploy_income = 10 }}, -- Fencer
}

return unit_energy