unitDef = {
    unitname            = [[builder]],
    name                = [[Builder]],
    description         = [[Builder]],
    acceleration        = 1.2,
    activateWhenBuilt   = true,
    brakeRate           = 1.5,
    buildCostMetal      = 150,
    buildDistance       = 128,
    builder             = true,

    buildoptions        = {
      [[factorycloak]],
      [[factoryshield]],
      [[factoryveh]],
      [[factorytank]],
      [[factoryspider]],
      [[factoryjump]],
      [[factoryamph]],
      [[factoryhover]],
      [[factoryplane]],
      [[factorygunship]],
      [[factoryship]],
    },

    buildPic            = [[amphcon.png]],
    canMove             = true,
    canPatrol           = true,
    category            = [[LAND UNARMED]],
    corpse              = [[DEAD]],
    customParams        = {},
    explodeAs           = [[BIG_UNITEX]],
    footprintX          = 2,
    footprintZ          = 2,
    iconType            = [[builder]],
    idleAutoHeal        = 5,
    idleTime            = 1800,
    leaveTracks         = true,
    maxDamage           = 850,
    maxSlope            = 36,
    maxVelocity         = 1.7,
    minCloakDistance    = 75,
    movementClass       = [[AKBOT2]],
    objectName          = [[amphcon.s3o]],
    selfDestructAs      = [[BIG_UNITEX]],
    script              = [[builder.lua]],
    showNanoSpray       = false,
    sightDistance       = 375,
    sonarDistance       = 375,
    trackOffset         = 0,
    trackStrength       = 8,
    trackStretch        = 1,
    trackType           = [[ChickenTrackPointy]],
    trackWidth          = 22,
    turnRate            = 1000,
    upright             = false,
    metalStorage        = 5000,
    energyStorage       = 5000,
    reclaimable         = false,
    workerTime          = 20,

    featureDefs         = {
      DEAD  = {
        blocking         = true,
        featureDead      = [[HEAP]],
        footprintX       = 2,
        footprintZ       = 2,
        object           = [[amphcon_dead.s3o]],
      },
      HEAP  = {
        blocking         = false,
        footprintX       = 2,
        footprintZ       = 2,
        object           = [[debris2x2a.s3o]],
      },
    },

  }

  return lowerkeys({builder = unitDef})
